export default {
  1: "Lorem.",
  2: "Lorem, ipsum.",
  3: "Lorem, ipsum dolor.",
  4: "Lorem ipsum dolor sit.",
  5: "Lorem ipsum dolor sit amet.",
  6: "Lorem ipsum dolor sit amet consectetur.",
  7: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  8: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
  9: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi!",
  10: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum, repudiandae.",
  12: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sed aliquam libero accusantium.",
  14: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Obcaecati ad asperiores rem autem nihil.",
  16: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero possimus similique eaque vel autem praesentium sunt?",
  18: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Fuga culpa aliquam hic earum exercitationem architecto! Eligendi, dicta ad!",
  20: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui error deserunt ipsam veritatis itaque molestiae dolores quos commodi repudiandae mollitia!",
  25: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro eos similique fugit autem, assumenda eum quis excepturi labore aspernatur fugiat obcaecati cumque aliquam, aliquid eius?",
  30: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias repellat, ex, voluptate magni voluptatum adipisci, saepe culpa dolorum rerum assumenda perferendis. Itaque quos alias, accusantium voluptates vel sed repellat magnam!",
  35: "Lorem ipsum dolor sit amet consectetur adipisicing elit. A eligendi fugit minima voluptatum. Animi totam accusantium recusandae iure veniam quisquam voluptatum, earum doloremque quibusdam, facilis, libero pariatur vero provident quae inventore modi illum? Error, commodi!",
  40: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur labore ea pariatur, facere ipsa autem dolor asperiores aperiam debitis quisquam, id repellat fuga molestias tenetur suscipit adipisci vero. Iusto, minus! Quibusdam, quia! Nemo tempore suscipit eos sed, voluptas possimus recusandae!",
  50: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Odit repellendus ratione ducimus! Exercitationem aliquid hic quasi iste impedit accusantium molestiae neque eius iusto omnis! Facere culpa illum suscipit in nihil reprehenderit harum ipsam sit sapiente animi labore repellendus expedita repellat, sed perspiciatis quasi natus ipsum necessitatibus quia pariatur aliquam amet?",
};
